name: README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Exécution quotidienne à minuit UTC (ajustez selon votre fuseau horaire)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v2

      - name: Utiliser Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Mettre à jour le nombre de jours
        run: |
          date_reference="2018-02-13"
          date_actuelle=$(date -u "+%Y-%m-%d")
          jours=$(( ($(date -d $date_actuelle +%s) - $(date -d $date_reference +%s)) / 86400 ))
          sed -i "s/{{DAYS_SINCE_CREATION}}/$jours/" template/README.md.tpl > README.md
          git config --local user.email "et.miracle@hotmail.fr"
          git config --local user.name "declick"
          git add README.md
          git commit -m "Mise à jour du nombre de jours" README.md
          git push
