name: Mise à jour du nombre de jours

on:
  schedule:
    - cron: '0 0 * * *' # Exécution quotidienne à minuit UTC (ajustez selon votre fuseau horaire)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v2

      - name: Utiliser Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Générer le contenu du README.md
        run: ./generate_readme.sh
        shell: bash

      - name: Commit et push des modifications
        run: |
          git config --local user.email "et.miracle@hotmail.fr"
          git config --local user.name "declick"
          git add README.md
          git commit -m "Mise à jour du nombre de jours" README.md
          git push
