name: README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '* * * * *' # Exécution quotidienne à minuit UTC (ajustez selon votre fuseau horaire)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v2

      - name: Mettre à jour le nombre de jours
        run: |
          date_reference="2018-02-13"
          date_actuelle=$(date -u "+%Y-%m-%d")
          jours=$(( ($(date -d $date_actuelle +%s) - $(date -d $date_reference +%s)) / 86400 ))
          sed -i "s/Le projet a été créé le .*/Le projet a été créé le $date_reference soit $jours jours./" README.md
          git config --local user.email "et.miracle@hotmail.fr"
          git config --local user.name "declick"
          git commit -m "Mise à jour du nombre de jours" README.md
          git push
