name: CI

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          DATE_INSCRIPTION="2018-02-13"
          DATE_ACTUELLE=$(date -u +"%Y-%m-%d")
          JOURS_ECOULES=$(( ( $(date -ud $DATE_ACTUELLE +'%s') - $(date -ud $DATE_INSCRIPTION +'%s') )/60/60/24 ))
  
          sed -i "s/Inscrit depuis : le .* jours/Inscrit depuis : le $DATE_INSCRIPTION soit $JOURS_ECOULES jours/" README.md

      - name: commit
        run: |
          git config --global user.email et.miracle@hotmail.fr
          git config --global user.name declick
          git add -a
          git commit -m "README update Automation" -a
          git push origin/main
