name: README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"  # À minuit chaque jour (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Days Since Registration
        run: |
          DATE_INSCRIPTION="2018-02-13"
          DATE_ACTUELLE=$(date -u +"%Y-%m-%d")
          JOURS_ECOULES=$(( ( $(date -ud $DATE_ACTUELLE +'%s') - $(date -ud $DATE_INSCRIPTION +'%s') )/60/60/24 ))
          sed -i "s/Inscrit depuis : le .* jours/Inscrit depuis : le $DATE_INSCRIPTION soit $JOURS_ECOULES jours/" README.md

          git config --local user.email "et.miracle@hotmail.fr"
          git config --local user.name "declick"
          git commit -am "Mise à jour du nombre de jours" # Ajoutez un commit pour les mises à jour automatiques
          git push # Poussez les modifications vers le dépôt
