
name: README

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '1 * * * *' # Exécution quotidienne à minuit UTC (ajustez selon votre fuseau horaire)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v2

      - name: Update Days Count
        run: |
         today=$(date +"%Y-%m-%d")
          created=$(date -d "2018-02-13" +"%Y-%m-%d")
          days=$(( ( $(date -ud "$today" +'%s') - $(date -ud "$created" +'%s') )/60/60/24 ))
          sed -i "s/Inscrit depuis le [0-9]*-[0-9]*-[0-9]* soit [0-9]* jours./Inscrit depuis le $created soit $days jours./" README.md

      - name: Commit et push des modifications
        run: |
          git config --local user.email "et.miracle@hotmail.fr"
          git config --local user.name "declick"
          git add .
          git commit -am "Update days count [skip ci]"
          git push


