name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Days Since Registration
        run: |
          DATE_INSCRIPTION="2018-02-13"
          DATE_ACTUELLE=$(date -u +"%Y-%m-%d")
          JOURS_ECOULES=$(( ( $(date -ud $DATE_ACTUELLE +'%s') - $(date -ud $DATE_INSCRIPTION +'%s') )/60/60/24 ))

          sed -i "s/Inscrit depuis : le .* jours/Inscrit depuis : le $DATE_INSCRIPTION soit $JOURS_ECOULES jours/" README.md

      - name: Commit and push changes
        run: |
          git add README.md
          git push -u origin main
          git commit -m "Auto update days since registration"
          git branch -M main
          git push
       
